name: "Build & Release"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
        #1 Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

        #2 setup java
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
        #3 setup Flutter
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
          channel: 'stable'

        #4 install dependencies
      - name: Install Dependencies
        run: flutter pub get

        #6 build apk
      - name: Build APK
        run: flutter build apk --release

        #7 build aab
      - name: Build appBundle
        run: flutter build appbundle

        #9 get those build to be available to download
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Releases
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
            

        #10 create release with those builds 
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk,build/app/outputs/bundle/release/app-release.aab,build/ios_build.tar.gz"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}  
